export const vibeThemes = {
  orange: {
    bg: "bg-orange-50",
    text: "text-orange-900",
    accent: "text-orange-400",
    statLabel: "text-orange-500",
    tabBg: "bg-orange-100",
    tabActive: "bg-orange-300 text-white",
    itemBg: "bg-orange-200",
  },
  blue: {
    bg: "bg-blue-50",
    text: "text-blue-900",
    accent: "text-blue-400",
    statLabel: "text-blue-500",
    tabBg: "bg-blue-100",
    tabActive: "bg-blue-300 text-white",
    itemBg: "bg-blue-200",
  },
  rose: {
    bg: "bg-rose-50",
    text: "text-rose-900",
    accent: "text-rose-400",
    statLabel: "text-rose-500",
    tabBg: "bg-rose-100",
    tabActive: "bg-rose-300 text-white",
    itemBg: "bg-rose-200",
  },
  green: {
    bg: "bg-green-50",
    text: "text-green-900",
    accent: "text-green-400",
    statLabel: "text-green-500",
    tabBg: "bg-green-100",
    tabActive: "bg-green-300 text-white",
    itemBg: "bg-green-200",
  },
};
